# Hyprland Configuration
# https://wiki.hypr.land/Configuring/

# Configuration paths
$hypr = ~/.config/hypr
$dms = $hypr/dms
$conf = $hypr/conf
$look = $conf/look
$rules = $conf/rules
$input = $conf/input

source = $conf/variables.conf
source = $conf/monitors.conf
source = $conf/execs.conf

source = $input/input.conf
source = $input/devices.conf
source = $input/gestures.conf

source = $look/general.conf
source = $look/decoration.conf
source = $look/animations.conf
source = $look/layouts.conf

source = $conf/misc.conf

source = $rules/rules-global.conf
source = $rules/rules-apps.conf
source = $conf/permissions.conf

# Dank material shell
source = $dms/colors.conf
source = $dms/outputs.conf
source = $dms/layout.conf
source = $dms/cursor.conf
source = $dms/binds.conf
