# https://wiki.hypr.land/Configuring/Variables/#decoration
decoration {
    rounding = $windowRounding
    rounding_power = 2

    # Change transparency of focused and unfocused windows
    active_opacity = 1.0
    inactive_opacity = 1.0

    shadow {
        enabled = $shadowEnabled
        range = $shadowRange
        render_power = $shadowRenderPower
        color = $shadowColour
    }

    # https://wiki.hypr.land/Configuring/Variables/#blur
    blur {
        enabled = $blurEnabled
        xray = $blurXray
        special = $blurSpecialWs
        ignore_opacity = true  # Allows opacity blurring
        new_optimizations = true
        popups = $blurPopups
        input_methods = $blurInputMethods
        size = $blurSize
        passes = $blurPasses
    }
}
