# https://wiki.hypr.land/Configuring/Variables/#general
general {
    gaps_workspaces = $workspaceGaps
    gaps_in = $windowGapsIn
    gaps_out = $windowGapsOut
    border_size = $windowBorderSize

    # https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
    col.active_border = $activeWindowBorderColour
    col.inactive_border = $inactiveWindowBorderColour

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = true

    # Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
    allow_tearing = false

    layout = dwindle
}

