# See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more
dwindle {
	preserve_split = true
	smart_split = false
	smart_resizing = true
}

# See https://wiki.hypr.land/Configuring/Master-Layout/ for more
master {
    new_status = master
}
