# ==================
# STARTUP APPS
# ==================
# Keyring and authentication daemon
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user start hyprland-session.target

#Phone link
exec-once = kdeconnectd

# Auto delete trash 30 days old
exec-once = trash-empty -f 30

# Wayland night light: adjust screen color temperature (6500K day -> 2800K night)
exec-once = wlsunset -l 46.814 -L -71.208 -T 6500 -t 2800
