#https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs
# device {
#     name = logitech-k850-8
#     kb_options = altwin:swap_alt_win
#     kb_layout = us,ca
#     kb_variant = ,
#     kb_model =
# }

